from dash import html, dcc
import pandas as pd

# ---------------------------------------------------------------------
# Common Plotly/Dash config
# ---------------------------------------------------------------------
COMMON_PLOTLY_CONFIG = {
    "displayModeBar": True,
    "displaylogo": False,
    "modeBarButtons": [
        ["pan2d", "zoomIn2d", "zoomOut2d", "zoom2d", "resetScale2d", "toImage"]
    ],
    "responsive": True
}

def get_layout(world_cup_overview_df: pd.DataFrame):    
    years = world_cup_overview_df["Year"].dropna().astype(int).sort_values().unique()
    min_year = int(years.min()) if len(years) > 0 else 1930
    max_year = int(years.max()) if len(years) > 0 else 2014
    
    N = 4
    slider_marks = {
        int(year): {
            'label': str(int(year)) if i % N == 0 else '',
            'style': {'transform': 'rotate(45deg)', 'white-space': 'nowrap', 'color': '#7f8c8d' if i % N == 0 else 'rgba(0,0,0,0)'}
        } for i, year in enumerate(years)
    }

    # --- Styles (Minor adjustments for consistency) ---
    app_container_style = {"maxWidth": "1600px", "margin": "20px auto", "padding": "20px"}
    header_style = {"textAlign": "center", "color": "#1A5276", "fontWeight": "bold", "marginBottom": "5px"}
    subtitle_style = {"textAlign": "center", "color": "#566573", "marginTop": "0px", "marginBottom": "25px"}
    card_style = {"border": "1px solid #d5dbdb", "padding": "20px", "borderRadius": "8px", "backgroundColor": "#ffffff", "boxShadow": "0 4px 8px rgba(0,0,0,0.05)", "marginBottom": "20px"}
    main_content_style = {"display": "flex", "flexDirection": "row", "gap": "20px"}
    left_column_style = {"flex": "2", "display": "flex", "flexDirection": "column"}
    right_column_style = {"flex": "1", "display": "flex", "flexDirection": "column"}
    plot_title_style = {"fontSize": "22px", "fontWeight": "700", "color": "#2C3E50"}
    small_label_style = {"fontSize": "14px", "color": "#566573", "marginBottom": "8px", "fontWeight": "bold"}
    initial_message_style = {"color":"#7f8c8d"}

    # --- Layout Structure ---
    # The main Div now uses an external stylesheet
    return html.Div([
        html.Div([
            html.H1("FIFA World Cup Interactive Explorer", style=header_style),
            html.P(f"Analyze every tournament from 1930 to {max_year}. Click a tournament to see the details.", style=subtitle_style),

            html.Div([
                # --- Left Column ---
                html.Div([
                    # Card for the main scatter plot
                    html.Div([
                        html.H3("World Cup Tournaments Overview", style=plot_title_style),
                        html.P("Each point is a tournament. Size represents attendance.", style={"color":"#566573"}),
                        html.Div(
                            id='scatter-plot-container',
                            children=[dcc.Graph(id="world-cup-overview-scatter", config=COMMON_PLOTLY_CONFIG, style={"height": "600px"})]
                        ),
                        html.Div([
                            html.Div("Select Year Range to Highlight:", style=small_label_style),
                            dcc.RangeSlider(id="year-range-slider", min=min_year, max=max_year, value=[2002, max_year], marks=slider_marks, step=None, tooltip={"placement": "bottom", "always_visible": False}),
                            html.Div(id="range-summary-output", style={'textAlign': 'center', 'marginTop': '15px', 'color': '#566573'})
                        ], style={"padding": "20px 10px 10px 10px"})
                    ], style=card_style),

                    html.Div(id='leaderboards-container', style={'display': 'flex', 'gap': '20px'}, children=[
                        # Panel for Golden Boot
                        html.Div(id="golden-boot-panel", style={'flex': '0 0 30%', **card_style}, children=[
                            html.H3("Top Scorers (Golden Boot)", style=plot_title_style),
                            html.Div(id="golden-boot-tracker") # Content will be generated by callback
                        ]),
                        html.Div(id="map-panel", style={'flex': 1, **card_style}, children=[
                            html.H3("Participating Nations", style=plot_title_style),
                            dcc.Graph(id="world-map-choropleth", style={'height': '400px'}, config={'displayModeBar': False})
                        ]),
                    ]),
                    
                    html.Div(id="h2h-panel", style={'display': 'none', **card_style}, children=[
                        html.H4("Head-to-Head Analysis", style={"color": "#1a5276"}),
                        html.P("Select an opponent to see their all-time World Cup history.", style={"fontSize": "14px", "color":"#566573"}),
                        dcc.Dropdown(id="opponent-selector-dropdown", placeholder="Select an opponent...", disabled=True),
                        html.Div(id="h2h-analysis-output", style={"marginTop": "15px"})
                    ])

                ], style=left_column_style),

                # --- Right Column ---
                 html.Div([
                    # Card for tournament details and team selection
                    html.Div(id="tournament-detail-panel", children=[
                        html.Button("Clear Selection", id="clear-selection-button", n_clicks=0, style={'float': 'right', 'display': 'none', 'marginBottom': '10px'}),
                        html.H3("Tournament Details", style=plot_title_style),
                        html.Div(id="tournament-summary", children=[html.P("Click on a tournament to see details.", style=initial_message_style)]),
                        html.Hr(),
                        html.Div("Select a Team:", style=small_label_style),
                        dcc.Dropdown(id="team-selector-dropdown", placeholder="Select a team...", disabled=True),
                    ], style=card_style),

                    html.Div(id="team-player-detail-panel", children=[
                        html.H3("Team & Player Details", style=plot_title_style),
                        html.Div(id="team-player-summary", children=[html.P("Select a team to see their performance.", style=initial_message_style)]),
                    ], style=card_style)
                ], style=right_column_style)

            ], style=main_content_style),

            html.Div("Data source: Kaggle FIFA World Cup Dataset.", style={"textAlign":"center","color":"#99a3a4","fontSize":"12px","marginTop":"30px"})
        ], style=app_container_style)
    ])
